### ISSUE TITLE
why are you using the awesome-go repository in your project?

### ISSUE THREAD

**Issue by avelino** [Gswaraw37/ProjectPenjualan#1]
https://github.com/Gswaraw37/ProjectPenjualan/blob/e25a495a6ced76907dff79c7b8c374f28a5e7811/go.mod#L8

I saw that you are using the awesome-go repository as your project package, is there a reason?

**Comment by Gswaraw37** [comment]
I saw youtube tutorials and I think it can make it easier for me to make project.
